name: Update PaperMC

on:
  schedule:
    #　日本時間午後8時00分に実行
    - cron: '0 11 * * *'

jobs:
  update-papermc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "Yukki_Moru@outlook.jp"
          git config --global user.name "YukkiMoru"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update PaperMC
        run: |
          LATEST_VERSION=$(curl -s https://papermc.io/api/v2/projects/paper | jq -r '.versions[-1]')
          LATEST_BUILD=$(curl -s https://papermc.io/api/v2/projects/paper/versions/$LATEST_VERSION/builds | jq -r '.builds | map(select(.channel == "default") | .build) | .[-1]')
          JAR_NAME="paper-$LATEST_VERSION-$LATEST_BUILD.jar"
          BRANCH_NAME="PaperMC-update-$LATEST_VERSION"

          git checkout -b $BRANCH_NAME

          # Download and build the latest PaperMC version with versioned filename
          curl -o $JAR_NAME https://papermc.io/api/v2/projects/paper/versions/$LATEST_VERSION/builds/$LATEST_BUILD/downloads/$JAR_NAME

          # You might need to stop the server before updating files
          # systemctl stop minecraft-server

          # Replace old PaperMC JAR with the new one
          cp $JAR_NAME Tower_Defense_Server/

          # Move to the server directory
          cd Tower_Defense_Server/

          # Update start.bat with the new JAR filename
          sed -i "s/java.exe -Xms8G -Xmx8G -jar paper-[0-9.]*-[0-9]*.jar/java.exe -Xms8G -Xmx8G -jar $JAR_NAME/" start.bat

          # Restart the server after updating
          # systemctl start minecraft-server

          git add .
          git commit -m "Update to PaperMC $LATEST_VERSION-$LATEST_BUILD"
          git push origin $BRANCH_NAME

          gh pr create --base main --head $BRANCH_NAME --title "Update to PaperMC $LATEST_VERSION-$LATEST_BUILD" --body "Automated update to the latest PaperMC version"
